import tempfile


class SSH(object):
    def __init__(self, ip, username, private_key, port=22):
        self.ip = ip
        self.username = username
        self.private_key = private_key
        self.port = port
        self.private_key_file = None
        self.config_file = None

    def user_host_and_port(self):
        if self.port == 22:
            return self.username + '@' + self.ip
        else:
            return "{user}@{host}:{port}".format(
                user=self.username,
                host=self.ip,
                port=str(self.port)
            )

    def key_file(self):
        if not self.private_key_file:
            self.private_key_file = tempfile.NamedTemporaryFile(
                prefix='dibctl_key_',
            )
            self.private_key_file.write(self.private_key)
            self.private_key_file.flush()
        return self.private_key_file.name

    def command_line(self):
        command_line = [
            "ssh",
            "-o", "StrictHostKeyChecking=no",
            "-o", "UserKnownHostsFile=/dev/null",
            "-o", "UpdateHostKeys=no",
            "-o", "PasswordAuthentication=no",
            "-i", self.key_file(),
            self.user_host_and_port()
        ]
        return command_line

    def connector(self):
        return 'ssh://%s' % self.ip

    def config(self):
        if not self.config_file:
            self.config_file = tempfile.NamedTemporaryFile(prefix="dibctl_config_")
            self.config_file.write('# Automatically generated by dibctl\n\n')
            self.config_file.write('Host %s\n' % self.ip)
            self.config_file.write('\tUser %s\n' % self.username)
            self.config_file.write('\tStrictHostKeyChecking no\n')
            self.config_file.write('\tUserKnownHostsFile /dev/null\n')
            self.config_file.write('\tUpdateHostKeys no\n')
            self.config_file.write('\tPasswordAuthentication no\n')
            self.config_file.write('\tIdentityFile %s\n' % self.key_file())
            self.config_file.write('\tPort %s\n' % self.port)
            self.config_file.flush()
        return self.config_file.name
